### ISSUE TITLE
Deploy Geocode Service ERROR

### ISSUE THREAD

**Issue by yuxiaoba** [gswk/earthquake-demo#1]
I have tried to deploy earthquake-demo in my cluster. But when I deploy geocode service, there are some problems happening.

----

## Infrastructure

Kubernetes 1.14 
Knative  0.10

----

```
$ kubectl apply -f geocoder-service.yaml

$ kubectl get ksvc
NAME                URL                                        LATESTCREATED             LATESTREADY               READY   REASON
geocoder            http://geocoder.default.dds.com            geocoder-d96lm                                      False   RevisionMissing

$ kubectl describe revision geocoder            
    Reason:                ExitCode1
    Status:                False
    Type:                  ContainerHealthy
    Last Transition Time:  2019-11-06T02:17:41Z
    Message:               Container failed with: /usr/local/bundle/gems/pg-1.1.3/lib/pg.rb:56:in `initialize': could not translate host name "geocodedb-postgresql.default.svc.cluster.local" to address: Name or service not known (PG::ConnectionBad)
                           from /usr/local/bundle/gems/pg-1.1.3/lib/pg.rb:56:in `new'
                           from /usr/local/bundle/gems/pg-1.1.3/lib/pg.rb:56:in `connect'
                           from app.rb:16:in `<main>'

    Reason:                ExitCode1
    Status:                False
    Type:                  Ready
    Last Transition Time:  2019-11-06T02:15:39Z
    Reason:                Deploying
    Status:                Unknown
    Type:                  ResourcesAvailable
  Image Digest:            index.docker.io/gswk/geocoder@sha256:8b6e329735a9aeacb47f953594dc3bc24b8b4d4de0a47fdad404ff4710926d6e
  Log URL:                 http://localhost:8001/api/v1/namespaces/knative-monitoring/services/kibana-logging/proxy/app/kibana#/discover?_a=(query:(match:(kubernetes.labels.knative-dev%2FrevisionUID:(query:'51f71496-003b-11ea-9280-5254004f8e0e',type:phrase))))
  Observed Generation:     1
  Service Name:            geocoder-d96lm
Events:
  Type     Reason         Age    From                 Message
  ----     ------         ----   ----                 -------
  Warning  InternalError  2m21s  revision-controller  failed to update deployment "geocoder-d96lm-deployment": Operation cannot be fulfilled on deployments.apps "geocoder-d96lm-deployment": the object has been modified; please apply your changes to the latest version and try again

```

It thinks that the service cannot connect the postgre. 

Then I check the source code in  `Getting Started with Knative`

```
DB_HOST = ENV["DB_HOST"] || 'localhost' 
DB_DATABASE = ENV["DB_DATABASE"] || 'geocode' 
DB_USER = ENV["DB_USER"] || 'postgres'
 DB_PASS = ENV["DB_PASS"] || 'password'
# Connect to the database and create table if it doesn't exist 
conn = PG.connect( dbname: DB_DATABASE, host: DB_HOST,    password: DB_PASS, user: DB_USER)
```

Is there lack the parameter 'port: 5432'?

**Comment by yuxiaoba** [comment]
I have found that I misconfigured something. It works well now.
Sorry, and I close this issue.
